server:
  port: 8989
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lyh46023424!
    hikari:
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接的自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000
      max-lifetime: 1800000
      #连接超时时间,默认30000
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: ctx
    settings:
      number_format: 0.##
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: true

#SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.mapper: debug



